name: run_maracluster
description: Run MaRaCluster for incremental spectral clustering of MGF files.
keywords:
  - maracluster
  - clustering
  - spectral
  - mgf
tools:
  - maracluster:
      description: |
        MaRaCluster is a tool for incremental clustering of mass spectrometry spectra.
      homepage: https://github.com/statisticalbiotechnology/maracluster
      documentation: https://github.com/statisticalbiotechnology/maracluster
input:
  - meta:
      type: string
      description: |
        Metadata string in format "species/instrument/charge" for the grouped MGF files.
  - mgf_files_path:
      type: file
      description: |
        List of MGF files to cluster, grouped by species, instrument, and charge.
      pattern: "*.mgf"
output:
  - meta:
      type: string
      description: |
        Metadata string passed through from input (format: "species/instrument/charge").
  - maracluster_results:
      type: file
      description: |
        TSV files containing clustering results from MaRaCluster. Files are named with cluster_threshold pattern (e.g., *_p30.tsv when cluster_threshold=30).
        The process will fail if no files matching the pattern are found, indicating that MaRaCluster did not produce the expected output.
      pattern: "*.tsv"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@bigbio"

