name: run_maracluster
description: Run MaRaCluster for incremental spectral clustering of MGF files.
keywords:
  - maracluster
  - clustering
  - spectral
  - mgf
tools:
  - maracluster:
      description: |
        MaRaCluster is a tool for incremental clustering of mass spectrometry spectra.
      homepage: https://github.com/statisticalbiotechnology/maracluster
      documentation: https://github.com/statisticalbiotechnology/maracluster
input:
  - mgf_files_path:
      type: file
      description: |
        List of MGF files to cluster, grouped by species, instrument, and charge.
      pattern: "*.mgf"
output:
  - maracluster_results:
      type: file
      description: |
        TSV files containing clustering results from MaRaCluster.
      pattern: "*.tsv"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@bigbio"

